// Original file: src/server/grpc/a2a.proto

export const TaskState = {
  TASK_STATE_UNSPECIFIED: 'TASK_STATE_UNSPECIFIED',
  TASK_STATE_SUBMITTED: 'TASK_STATE_SUBMITTED',
  TASK_STATE_WORKING: 'TASK_STATE_WORKING',
  TASK_STATE_COMPLETED: 'TASK_STATE_COMPLETED',
  TASK_STATE_FAILED: 'TASK_STATE_FAILED',
  TASK_STATE_CANCELLED: 'TASK_STATE_CANCELLED',
  TASK_STATE_INPUT_REQUIRED: 'TASK_STATE_INPUT_REQUIRED',
  TASK_STATE_REJECTED: 'TASK_STATE_REJECTED',
  TASK_STATE_AUTH_REQUIRED: 'TASK_STATE_AUTH_REQUIRED',
} as const;

export type TaskState =
  | 'TASK_STATE_UNSPECIFIED'
  | 0
  | 'TASK_STATE_SUBMITTED'
  | 1
  | 'TASK_STATE_WORKING'
  | 2
  | 'TASK_STATE_COMPLETED'
  | 3
  | 'TASK_STATE_FAILED'
  | 4
  | 'TASK_STATE_CANCELLED'
  | 5
  | 'TASK_STATE_INPUT_REQUIRED'
  | 6
  | 'TASK_STATE_REJECTED'
  | 7
  | 'TASK_STATE_AUTH_REQUIRED'
  | 8

export type TaskState__Output = typeof TaskState[keyof typeof TaskState]
