// @generated by protobuf-ts 2.11.1 with parameter server_grpc1,client_grpc1
// @generated from protobuf file "a2a.proto" (package "a2a.v1", syntax proto3)
// tslint:disable
import { A2AService } from "./a2a";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { Empty } from "./google/protobuf/empty";
import type { DeleteTaskPushNotificationConfigRequest } from "./a2a";
import type { AgentCard } from "./a2a";
import type { GetExtendedAgentCardRequest } from "./a2a";
import type { ListTaskPushNotificationConfigResponse } from "./a2a";
import type { ListTaskPushNotificationConfigRequest } from "./a2a";
import type { GetTaskPushNotificationConfigRequest } from "./a2a";
import type { TaskPushNotificationConfig } from "./a2a";
import type { SetTaskPushNotificationConfigRequest } from "./a2a";
import type { SubscribeToTaskRequest } from "./a2a";
import type { CancelTaskRequest } from "./a2a";
import type { ListTasksResponse } from "./a2a";
import type { ListTasksRequest } from "./a2a";
import type { Task } from "./a2a";
import type { GetTaskRequest } from "./a2a";
import type { StreamResponse } from "./a2a";
import type { SendMessageResponse } from "./a2a";
import type { SendMessageRequest } from "./a2a";
import * as grpc from "@grpc/grpc-js";
/**
 * A2AService defines the operations of the A2A protocol.
 *
 * @generated from protobuf service a2a.v1.A2AService
 */
export interface IA2AServiceClient {
    /**
     * Send a message to the agent.
     *
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: SendMessageRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SendMessageResponse) => void): grpc.ClientUnaryCall;
    sendMessage(input: SendMessageRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: SendMessageResponse) => void): grpc.ClientUnaryCall;
    sendMessage(input: SendMessageRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SendMessageResponse) => void): grpc.ClientUnaryCall;
    sendMessage(input: SendMessageRequest, callback: (err: grpc.ServiceError | null, value?: SendMessageResponse) => void): grpc.ClientUnaryCall;
    /**
     * SendStreamingMessage is a streaming version of SendMessage.
     *
     * @generated from protobuf rpc: SendStreamingMessage
     */
    sendStreamingMessage(input: SendMessageRequest, metadata?: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientReadableStream<StreamResponse>;
    sendStreamingMessage(input: SendMessageRequest, options?: grpc.CallOptions): grpc.ClientReadableStream<StreamResponse>;
    /**
     * Get the current state of a task from the agent.
     *
     * @generated from protobuf rpc: GetTask
     */
    getTask(input: GetTaskRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Task) => void): grpc.ClientUnaryCall;
    getTask(input: GetTaskRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Task) => void): grpc.ClientUnaryCall;
    getTask(input: GetTaskRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Task) => void): grpc.ClientUnaryCall;
    getTask(input: GetTaskRequest, callback: (err: grpc.ServiceError | null, value?: Task) => void): grpc.ClientUnaryCall;
    /**
     * List tasks with optional filtering and pagination.
     *
     * @generated from protobuf rpc: ListTasks
     */
    listTasks(input: ListTasksRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ListTasksResponse) => void): grpc.ClientUnaryCall;
    listTasks(input: ListTasksRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: ListTasksResponse) => void): grpc.ClientUnaryCall;
    listTasks(input: ListTasksRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ListTasksResponse) => void): grpc.ClientUnaryCall;
    listTasks(input: ListTasksRequest, callback: (err: grpc.ServiceError | null, value?: ListTasksResponse) => void): grpc.ClientUnaryCall;
    /**
     * Cancel a task.
     *
     * @generated from protobuf rpc: CancelTask
     */
    cancelTask(input: CancelTaskRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Task) => void): grpc.ClientUnaryCall;
    cancelTask(input: CancelTaskRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Task) => void): grpc.ClientUnaryCall;
    cancelTask(input: CancelTaskRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Task) => void): grpc.ClientUnaryCall;
    cancelTask(input: CancelTaskRequest, callback: (err: grpc.ServiceError | null, value?: Task) => void): grpc.ClientUnaryCall;
    /**
     * SubscribeToTask allows subscribing to task updates for tasks not in terminal state.
     * Returns UnsupportedOperationError if task is in terminal state (completed, failed, cancelled, rejected).
     *
     * @generated from protobuf rpc: SubscribeToTask
     */
    subscribeToTask(input: SubscribeToTaskRequest, metadata?: grpc.Metadata, options?: grpc.CallOptions): grpc.ClientReadableStream<StreamResponse>;
    subscribeToTask(input: SubscribeToTaskRequest, options?: grpc.CallOptions): grpc.ClientReadableStream<StreamResponse>;
    /**
     * Set a push notification config for a task.
     *
     * @generated from protobuf rpc: SetTaskPushNotificationConfig
     */
    setTaskPushNotificationConfig(input: SetTaskPushNotificationConfigRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void): grpc.ClientUnaryCall;
    setTaskPushNotificationConfig(input: SetTaskPushNotificationConfigRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void): grpc.ClientUnaryCall;
    setTaskPushNotificationConfig(input: SetTaskPushNotificationConfigRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void): grpc.ClientUnaryCall;
    setTaskPushNotificationConfig(input: SetTaskPushNotificationConfigRequest, callback: (err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void): grpc.ClientUnaryCall;
    /**
     * Get a push notification config for a task.
     *
     * @generated from protobuf rpc: GetTaskPushNotificationConfig
     */
    getTaskPushNotificationConfig(input: GetTaskPushNotificationConfigRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void): grpc.ClientUnaryCall;
    getTaskPushNotificationConfig(input: GetTaskPushNotificationConfigRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void): grpc.ClientUnaryCall;
    getTaskPushNotificationConfig(input: GetTaskPushNotificationConfigRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void): grpc.ClientUnaryCall;
    getTaskPushNotificationConfig(input: GetTaskPushNotificationConfigRequest, callback: (err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void): grpc.ClientUnaryCall;
    /**
     * Get a list of push notifications configured for a task.
     *
     * @generated from protobuf rpc: ListTaskPushNotificationConfig
     */
    listTaskPushNotificationConfig(input: ListTaskPushNotificationConfigRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ListTaskPushNotificationConfigResponse) => void): grpc.ClientUnaryCall;
    listTaskPushNotificationConfig(input: ListTaskPushNotificationConfigRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: ListTaskPushNotificationConfigResponse) => void): grpc.ClientUnaryCall;
    listTaskPushNotificationConfig(input: ListTaskPushNotificationConfigRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ListTaskPushNotificationConfigResponse) => void): grpc.ClientUnaryCall;
    listTaskPushNotificationConfig(input: ListTaskPushNotificationConfigRequest, callback: (err: grpc.ServiceError | null, value?: ListTaskPushNotificationConfigResponse) => void): grpc.ClientUnaryCall;
    /**
     * GetExtendedAgentCard returns the extended agent card for authenticated agents.
     *
     * @generated from protobuf rpc: GetExtendedAgentCard
     */
    getExtendedAgentCard(input: GetExtendedAgentCardRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: AgentCard) => void): grpc.ClientUnaryCall;
    getExtendedAgentCard(input: GetExtendedAgentCardRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: AgentCard) => void): grpc.ClientUnaryCall;
    getExtendedAgentCard(input: GetExtendedAgentCardRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: AgentCard) => void): grpc.ClientUnaryCall;
    getExtendedAgentCard(input: GetExtendedAgentCardRequest, callback: (err: grpc.ServiceError | null, value?: AgentCard) => void): grpc.ClientUnaryCall;
    /**
     * Delete a push notification config for a task.
     *
     * @generated from protobuf rpc: DeleteTaskPushNotificationConfig
     */
    deleteTaskPushNotificationConfig(input: DeleteTaskPushNotificationConfigRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Empty) => void): grpc.ClientUnaryCall;
    deleteTaskPushNotificationConfig(input: DeleteTaskPushNotificationConfigRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: Empty) => void): grpc.ClientUnaryCall;
    deleteTaskPushNotificationConfig(input: DeleteTaskPushNotificationConfigRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: Empty) => void): grpc.ClientUnaryCall;
    deleteTaskPushNotificationConfig(input: DeleteTaskPushNotificationConfigRequest, callback: (err: grpc.ServiceError | null, value?: Empty) => void): grpc.ClientUnaryCall;
}
/**
 * A2AService defines the operations of the A2A protocol.
 *
 * @generated from protobuf service a2a.v1.A2AService
 */
export class A2AServiceClient extends grpc.Client implements IA2AServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * Send a message to the agent.
     *
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage(input: SendMessageRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SendMessageResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SendMessageResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: SendMessageResponse) => void)): grpc.ClientUnaryCall {
        const method = A2AService.methods[0];
        return this.makeUnaryRequest<SendMessageRequest, SendMessageResponse>(`/${A2AService.typeName}/${method.name}`, (value: SendMessageRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): SendMessageResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * SendStreamingMessage is a streaming version of SendMessage.
     *
     * @generated from protobuf rpc: SendStreamingMessage
     */
    sendStreamingMessage(input: SendMessageRequest, metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientReadableStream<StreamResponse> {
        const method = A2AService.methods[1];
        return this.makeServerStreamRequest<SendMessageRequest, StreamResponse>(`/${A2AService.typeName}/${method.name}`, (value: SendMessageRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): StreamResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), options);
    }
    /**
     * Get the current state of a task from the agent.
     *
     * @generated from protobuf rpc: GetTask
     */
    getTask(input: GetTaskRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Task) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Task) => void), callback?: ((err: grpc.ServiceError | null, value?: Task) => void)): grpc.ClientUnaryCall {
        const method = A2AService.methods[2];
        return this.makeUnaryRequest<GetTaskRequest, Task>(`/${A2AService.typeName}/${method.name}`, (value: GetTaskRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): Task => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * List tasks with optional filtering and pagination.
     *
     * @generated from protobuf rpc: ListTasks
     */
    listTasks(input: ListTasksRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ListTasksResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ListTasksResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: ListTasksResponse) => void)): grpc.ClientUnaryCall {
        const method = A2AService.methods[3];
        return this.makeUnaryRequest<ListTasksRequest, ListTasksResponse>(`/${A2AService.typeName}/${method.name}`, (value: ListTasksRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): ListTasksResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Cancel a task.
     *
     * @generated from protobuf rpc: CancelTask
     */
    cancelTask(input: CancelTaskRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Task) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Task) => void), callback?: ((err: grpc.ServiceError | null, value?: Task) => void)): grpc.ClientUnaryCall {
        const method = A2AService.methods[4];
        return this.makeUnaryRequest<CancelTaskRequest, Task>(`/${A2AService.typeName}/${method.name}`, (value: CancelTaskRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): Task => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * SubscribeToTask allows subscribing to task updates for tasks not in terminal state.
     * Returns UnsupportedOperationError if task is in terminal state (completed, failed, cancelled, rejected).
     *
     * @generated from protobuf rpc: SubscribeToTask
     */
    subscribeToTask(input: SubscribeToTaskRequest, metadata?: grpc.Metadata | grpc.CallOptions, options?: grpc.CallOptions): grpc.ClientReadableStream<StreamResponse> {
        const method = A2AService.methods[5];
        return this.makeServerStreamRequest<SubscribeToTaskRequest, StreamResponse>(`/${A2AService.typeName}/${method.name}`, (value: SubscribeToTaskRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): StreamResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), options);
    }
    /**
     * Set a push notification config for a task.
     *
     * @generated from protobuf rpc: SetTaskPushNotificationConfig
     */
    setTaskPushNotificationConfig(input: SetTaskPushNotificationConfigRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void), callback?: ((err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void)): grpc.ClientUnaryCall {
        const method = A2AService.methods[6];
        return this.makeUnaryRequest<SetTaskPushNotificationConfigRequest, TaskPushNotificationConfig>(`/${A2AService.typeName}/${method.name}`, (value: SetTaskPushNotificationConfigRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): TaskPushNotificationConfig => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Get a push notification config for a task.
     *
     * @generated from protobuf rpc: GetTaskPushNotificationConfig
     */
    getTaskPushNotificationConfig(input: GetTaskPushNotificationConfigRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void), callback?: ((err: grpc.ServiceError | null, value?: TaskPushNotificationConfig) => void)): grpc.ClientUnaryCall {
        const method = A2AService.methods[7];
        return this.makeUnaryRequest<GetTaskPushNotificationConfigRequest, TaskPushNotificationConfig>(`/${A2AService.typeName}/${method.name}`, (value: GetTaskPushNotificationConfigRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): TaskPushNotificationConfig => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Get a list of push notifications configured for a task.
     *
     * @generated from protobuf rpc: ListTaskPushNotificationConfig
     */
    listTaskPushNotificationConfig(input: ListTaskPushNotificationConfigRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ListTaskPushNotificationConfigResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ListTaskPushNotificationConfigResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: ListTaskPushNotificationConfigResponse) => void)): grpc.ClientUnaryCall {
        const method = A2AService.methods[8];
        return this.makeUnaryRequest<ListTaskPushNotificationConfigRequest, ListTaskPushNotificationConfigResponse>(`/${A2AService.typeName}/${method.name}`, (value: ListTaskPushNotificationConfigRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): ListTaskPushNotificationConfigResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * GetExtendedAgentCard returns the extended agent card for authenticated agents.
     *
     * @generated from protobuf rpc: GetExtendedAgentCard
     */
    getExtendedAgentCard(input: GetExtendedAgentCardRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: AgentCard) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: AgentCard) => void), callback?: ((err: grpc.ServiceError | null, value?: AgentCard) => void)): grpc.ClientUnaryCall {
        const method = A2AService.methods[9];
        return this.makeUnaryRequest<GetExtendedAgentCardRequest, AgentCard>(`/${A2AService.typeName}/${method.name}`, (value: GetExtendedAgentCardRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): AgentCard => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Delete a push notification config for a task.
     *
     * @generated from protobuf rpc: DeleteTaskPushNotificationConfig
     */
    deleteTaskPushNotificationConfig(input: DeleteTaskPushNotificationConfigRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Empty) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: Empty) => void), callback?: ((err: grpc.ServiceError | null, value?: Empty) => void)): grpc.ClientUnaryCall {
        const method = A2AService.methods[10];
        return this.makeUnaryRequest<DeleteTaskPushNotificationConfigRequest, Empty>(`/${A2AService.typeName}/${method.name}`, (value: DeleteTaskPushNotificationConfigRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): Empty => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
