// @generated by protobuf-ts 2.11.1 with parameter server_grpc1,client_grpc1
// @generated from protobuf file "a2a.proto" (package "a2a.v1", syntax proto3)
// tslint:disable
import { Empty } from "./google/protobuf/empty";
import { DeleteTaskPushNotificationConfigRequest } from "./a2a";
import { AgentCard } from "./a2a";
import { GetExtendedAgentCardRequest } from "./a2a";
import { ListTaskPushNotificationConfigResponse } from "./a2a";
import { ListTaskPushNotificationConfigRequest } from "./a2a";
import { GetTaskPushNotificationConfigRequest } from "./a2a";
import { TaskPushNotificationConfig } from "./a2a";
import { SetTaskPushNotificationConfigRequest } from "./a2a";
import { SubscribeToTaskRequest } from "./a2a";
import { CancelTaskRequest } from "./a2a";
import { ListTasksResponse } from "./a2a";
import { ListTasksRequest } from "./a2a";
import { Task } from "./a2a";
import { GetTaskRequest } from "./a2a";
import { StreamResponse } from "./a2a";
import { SendMessageResponse } from "./a2a";
import { SendMessageRequest } from "./a2a";
import type * as grpc from "@grpc/grpc-js";
/**
 * A2AService defines the operations of the A2A protocol.
 *
 * @generated from protobuf service a2a.v1.A2AService
 */
export interface IA2AService extends grpc.UntypedServiceImplementation {
    /**
     * Send a message to the agent.
     *
     * @generated from protobuf rpc: SendMessage
     */
    sendMessage: grpc.handleUnaryCall<SendMessageRequest, SendMessageResponse>;
    /**
     * SendStreamingMessage is a streaming version of SendMessage.
     *
     * @generated from protobuf rpc: SendStreamingMessage
     */
    sendStreamingMessage: grpc.handleServerStreamingCall<SendMessageRequest, StreamResponse>;
    /**
     * Get the current state of a task from the agent.
     *
     * @generated from protobuf rpc: GetTask
     */
    getTask: grpc.handleUnaryCall<GetTaskRequest, Task>;
    /**
     * List tasks with optional filtering and pagination.
     *
     * @generated from protobuf rpc: ListTasks
     */
    listTasks: grpc.handleUnaryCall<ListTasksRequest, ListTasksResponse>;
    /**
     * Cancel a task.
     *
     * @generated from protobuf rpc: CancelTask
     */
    cancelTask: grpc.handleUnaryCall<CancelTaskRequest, Task>;
    /**
     * SubscribeToTask allows subscribing to task updates for tasks not in terminal state.
     * Returns UnsupportedOperationError if task is in terminal state (completed, failed, cancelled, rejected).
     *
     * @generated from protobuf rpc: SubscribeToTask
     */
    subscribeToTask: grpc.handleServerStreamingCall<SubscribeToTaskRequest, StreamResponse>;
    /**
     * Set a push notification config for a task.
     *
     * @generated from protobuf rpc: SetTaskPushNotificationConfig
     */
    setTaskPushNotificationConfig: grpc.handleUnaryCall<SetTaskPushNotificationConfigRequest, TaskPushNotificationConfig>;
    /**
     * Get a push notification config for a task.
     *
     * @generated from protobuf rpc: GetTaskPushNotificationConfig
     */
    getTaskPushNotificationConfig: grpc.handleUnaryCall<GetTaskPushNotificationConfigRequest, TaskPushNotificationConfig>;
    /**
     * Get a list of push notifications configured for a task.
     *
     * @generated from protobuf rpc: ListTaskPushNotificationConfig
     */
    listTaskPushNotificationConfig: grpc.handleUnaryCall<ListTaskPushNotificationConfigRequest, ListTaskPushNotificationConfigResponse>;
    /**
     * GetExtendedAgentCard returns the extended agent card for authenticated agents.
     *
     * @generated from protobuf rpc: GetExtendedAgentCard
     */
    getExtendedAgentCard: grpc.handleUnaryCall<GetExtendedAgentCardRequest, AgentCard>;
    /**
     * Delete a push notification config for a task.
     *
     * @generated from protobuf rpc: DeleteTaskPushNotificationConfig
     */
    deleteTaskPushNotificationConfig: grpc.handleUnaryCall<DeleteTaskPushNotificationConfigRequest, Empty>;
}
/**
 * @grpc/grpc-js definition for the protobuf service a2a.v1.A2AService.
 *
 * Usage: Implement the interface IA2AService and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: IA2AService = ...
 * server.addService(a2AServiceDefinition, service);
 * ```
 */
export const a2AServiceDefinition: grpc.ServiceDefinition<IA2AService> = {
    sendMessage: {
        path: "/a2a.v1.A2AService/SendMessage",
        originalName: "SendMessage",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => SendMessageResponse.fromBinary(bytes),
        requestDeserialize: bytes => SendMessageRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(SendMessageResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(SendMessageRequest.toBinary(value))
    },
    sendStreamingMessage: {
        path: "/a2a.v1.A2AService/SendStreamingMessage",
        originalName: "SendStreamingMessage",
        requestStream: false,
        responseStream: true,
        responseDeserialize: bytes => StreamResponse.fromBinary(bytes),
        requestDeserialize: bytes => SendMessageRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(StreamResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(SendMessageRequest.toBinary(value))
    },
    getTask: {
        path: "/a2a.v1.A2AService/GetTask",
        originalName: "GetTask",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => Task.fromBinary(bytes),
        requestDeserialize: bytes => GetTaskRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(Task.toBinary(value)),
        requestSerialize: value => Buffer.from(GetTaskRequest.toBinary(value))
    },
    listTasks: {
        path: "/a2a.v1.A2AService/ListTasks",
        originalName: "ListTasks",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => ListTasksResponse.fromBinary(bytes),
        requestDeserialize: bytes => ListTasksRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(ListTasksResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(ListTasksRequest.toBinary(value))
    },
    cancelTask: {
        path: "/a2a.v1.A2AService/CancelTask",
        originalName: "CancelTask",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => Task.fromBinary(bytes),
        requestDeserialize: bytes => CancelTaskRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(Task.toBinary(value)),
        requestSerialize: value => Buffer.from(CancelTaskRequest.toBinary(value))
    },
    subscribeToTask: {
        path: "/a2a.v1.A2AService/SubscribeToTask",
        originalName: "SubscribeToTask",
        requestStream: false,
        responseStream: true,
        responseDeserialize: bytes => StreamResponse.fromBinary(bytes),
        requestDeserialize: bytes => SubscribeToTaskRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(StreamResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(SubscribeToTaskRequest.toBinary(value))
    },
    setTaskPushNotificationConfig: {
        path: "/a2a.v1.A2AService/SetTaskPushNotificationConfig",
        originalName: "SetTaskPushNotificationConfig",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => TaskPushNotificationConfig.fromBinary(bytes),
        requestDeserialize: bytes => SetTaskPushNotificationConfigRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(TaskPushNotificationConfig.toBinary(value)),
        requestSerialize: value => Buffer.from(SetTaskPushNotificationConfigRequest.toBinary(value))
    },
    getTaskPushNotificationConfig: {
        path: "/a2a.v1.A2AService/GetTaskPushNotificationConfig",
        originalName: "GetTaskPushNotificationConfig",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => TaskPushNotificationConfig.fromBinary(bytes),
        requestDeserialize: bytes => GetTaskPushNotificationConfigRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(TaskPushNotificationConfig.toBinary(value)),
        requestSerialize: value => Buffer.from(GetTaskPushNotificationConfigRequest.toBinary(value))
    },
    listTaskPushNotificationConfig: {
        path: "/a2a.v1.A2AService/ListTaskPushNotificationConfig",
        originalName: "ListTaskPushNotificationConfig",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => ListTaskPushNotificationConfigResponse.fromBinary(bytes),
        requestDeserialize: bytes => ListTaskPushNotificationConfigRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(ListTaskPushNotificationConfigResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(ListTaskPushNotificationConfigRequest.toBinary(value))
    },
    getExtendedAgentCard: {
        path: "/a2a.v1.A2AService/GetExtendedAgentCard",
        originalName: "GetExtendedAgentCard",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => AgentCard.fromBinary(bytes),
        requestDeserialize: bytes => GetExtendedAgentCardRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(AgentCard.toBinary(value)),
        requestSerialize: value => Buffer.from(GetExtendedAgentCardRequest.toBinary(value))
    },
    deleteTaskPushNotificationConfig: {
        path: "/a2a.v1.A2AService/DeleteTaskPushNotificationConfig",
        originalName: "DeleteTaskPushNotificationConfig",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => Empty.fromBinary(bytes),
        requestDeserialize: bytes => DeleteTaskPushNotificationConfigRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(Empty.toBinary(value)),
        requestSerialize: value => Buffer.from(DeleteTaskPushNotificationConfigRequest.toBinary(value))
    }
};
